import fs from "fs/promises";
import path from "path";

export async function createAgent({
  agentId,
  name,
  preset,
  owner,
  persona,
  emoji,
  model,
  authMode
}) {
  const outputDir = path.resolve("output", agentId);

  try {
    await fs.access(outputDir);
    throw new Error(`Output folder already exists: ${outputDir}`);
  } catch (error) {
    if (error.code !== "ENOENT") {
      throw error;
    }
  }

  await fs.mkdir(outputDir, { recursive: true });
  await fs.mkdir(path.join(outputDir, "memory"), { recursive: true });

  const identityContent = `# IDENTITY.md

- Name: ${name}
- Agent ID: ${agentId}
- Emoji: ${emoji}
- Preset: ${preset}
`;

  const soulContent = `# SOUL.md

You are ${name}.
Your personality: ${persona}
You help ${owner} using the ${preset} preset.
`;

  const agentsContent = `# AGENTS.md

- Keep responses helpful
- Keep workspace organized
- This agent was generated by maskclaw-agent
- Preferred model: ${model}
- Auth mode: ${authMode}
`;

  const userContent = `# USER.md

- Owner: ${owner}
- Preferred style: ${persona}
`;

  const manifest = {
    agentId,
    name,
    preset,
    owner,
    persona,
    emoji,
    model,
    authMode,
    createdAt: new Date().toISOString()
  };

  await fs.writeFile(path.join(outputDir, "IDENTITY.md"), identityContent, "utf8");
  await fs.writeFile(path.join(outputDir, "SOUL.md"), soulContent, "utf8");
  await fs.writeFile(path.join(outputDir, "AGENTS.md"), agentsContent, "utf8");
  await fs.writeFile(path.join(outputDir, "USER.md"), userContent, "utf8");
  await fs.writeFile(
    path.join(outputDir, "agent.manifest.json"),
    JSON.stringify(manifest, null, 2),
    "utf8"
  );

  return {
    outputDir,
    manifest
  };
}
